import type { TranslationKey } from '@/lib/i18n';

export type FinanceSection = 'overview' | 'income' | 'expenses' | 'payroll' | 'transactions';

export const financeRoutes: Record<FinanceSection, string> = {
  overview: '/finance',
  income: '/finance/income',
  expenses: '/finance/expenses',
  payroll: '/finance/payroll',
  transactions: '/finance/transactions',
};

export const currentFinancePeriod = () => {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'Asia/Tashkent',
    year: 'numeric',
    month: '2-digit',
  }).formatToParts(new Date());
  const year = parts.find((part) => part.type === 'year')?.value ?? '2026';
  const month = parts.find((part) => part.type === 'month')?.value ?? '01';
  return `${year}-${month}`;
};

type Translate = (key: TranslationKey) => string;

export const financeCopy = (t: Translate) => ({
  module: t('financeCenterModule'),
  overview: t('financeCenterOverview'),
  income: t('financeCenterIncome'),
  expenses: t('expenses'),
  payroll: t('financeCenterPayroll'),
  transactions: t('financeCenterTransactions'),
  subtitle: t('financeCenterSubtitle'),
  incomeSubtitle: t('financeCenterIncomeSubtitle'),
  expensesSubtitle: t('financeCenterExpensesSubtitle'),
  payrollSubtitle: t('financeCenterPayrollSubtitle'),
  transactionsSubtitle: t('financeCenterTransactionsSubtitle'),
  addExpense: t('addExpense'),
  configureSalary: t('financeCenterConfigureSalary'),
  netProfit: t('financeCenterNetProfit'),
  revenue: t('revenue'),
  allExpenses: t('financeCenterAllExpenses'),
  margin: t('financeCenterMargin'),
  duePayroll: t('financeCenterDuePayroll'),
  profitFormula: t('financeCenterProfitFormula'),
  vsPreviousMonth: t('adminVsPreviousMonth'),
  profitTrend: t('financeCenterProfitTrend'),
  expenseStructure: t('financeCenterExpenseStructure'),
  recentTransactions: t('financeCenterRecentTransactions'),
  seeAllTransactions: t('financeCenterSeeAllTransactions'),
  noData: t('financeCenterNoData'),
  loading: t('financeCenterLoading'),
  retry: t('retrySend'),
  methodology: t('financeCenterMethodology'),
  date: t('dateColumn'),
  operation: t('financeCenterOperation'),
  category: t('financeCenterCategory'),
  counterparty: t('financeCenterCounterparty'),
  status: t('status'),
  amount: t('amount'),
  method: t('financeCenterMethod'),
  customer: t('financeCenterCustomer'),
  course: t('course'),
  manager: t('manager'),
  paymentCount: t('financeCenterPaymentCount'),
  averagePayment: t('financeCenterAveragePayment'),
  refunds: t('financeCenterRefunds'),
  incomeRegistry: t('financeCenterIncomeRegistry'),
  totalRecognized: t('financeCenterTotalRecognized'),
  operatingPaid: t('financeCenterOperatingPaid'),
  marketing: t('marketingTab'),
  planned: t('financeCenterPlanned'),
  expenseRegistry: t('financeCenterExpenseRegistry'),
  source: t('source'),
  vendor: t('financeCenterVendor'),
  actions: t('actions'),
  pay: t('financeCenterPay'),
  cancel: t('financeCenterCancelExpense'),
  paid: t('paymentStatusPaid'),
  pending: t('financeCenterPending'),
  unconfigured: t('financeCenterUnconfigured'),
  approved: t('financeCenterApproved'),
  cancelled: t('financeCenterCancelled'),
  refunded: t('financeCenterRefunded'),
  recorded: t('financeCenterRecorded'),
  marketingSource: t('financeCenterMarketingSource'),
  operatingSource: t('financeCenterOperatingSource'),
  salaryFund: t('financeCenterSalaryFund'),
  paidPayroll: t('financeCenterPaidPayroll'),
  remainingPayroll: t('financeCenterRemainingPayroll'),
  payrollStatement: t('financeCenterPayrollStatement'),
  employee: t('financeCenterEmployee'),
  position: t('position'),
  salary: t('financeCenterSalary'),
  bonus: t('financeCenterBonus'),
  deduction: t('financeCenterDeduction'),
  payoutAmount: t('financeCenterPayoutAmount'),
  payAll: t('financeCenterPayAll'),
  currentSalary: t('financeCenterCurrentSalary'),
  effectiveFrom: t('financeCenterEffectiveFrom'),
  previousSalary: t('financeCenterPreviousSalary'),
  salaryHistory: t('financeCenterSalaryHistory'),
  noSalaryHistory: t('financeCenterNoSalaryHistory'),
  selectEmployee: t('financeCenterSelectEmployee'),
  expenseDialogTitle: t('financeCenterExpenseDialogTitle'),
  expenseDialogDescription: t('financeCenterExpenseDialogDescription'),
  title: t('financeCenterTitle'),
  description: t('description'),
  expenseDate: t('financeCenterExpenseDate'),
  paymentStatus: t('financeCenterPaymentStatus'),
  saveExpense: t('financeCenterSaveExpense'),
  salaryDialogTitle: t('financeCenterSalaryDialogTitle'),
  salaryDialogDescription: t('financeCenterSalaryDialogDescription'),
  effectiveMonth: t('financeCenterEffectiveMonth'),
  note: t('comment'),
  saveSalary: t('financeCenterSaveSalary'),
  payoutDialogTitle: t('financeCenterPayoutDialogTitle'),
  calculationMonth: t('financeCenterCalculationMonth'),
  payoutTotal: t('financeCenterPayoutTotal'),
  paymentMethod: t('financeCenterPayoutMethod'),
  confirmPayout: t('financeCenterConfirmPayout'),
  batchTitle: t('financeCenterBatchTitle'),
  batchDescription: t('financeCenterBatchDescription'),
  confirmBatch: t('financeCenterConfirmBatch'),
  formCancel: t('cancel'),
  saved: t('financeCenterSaved'),
  payoutSaved: t('financeCenterPayoutSaved'),
  batchSaved: t('financeCenterBatchSaved'),
  expensePaid: t('financeCenterExpensePaid'),
  expenseCancelled: t('financeCenterExpenseCancelled'),
  error: t('financeCenterError'),
  cancellationReason: t('financeCenterCancellationReason'),
  confirmCancel: t('financeCenterConfirmCancel'),
  cash: t('paymentMethodCash'),
  transfer: t('paymentMethodTransfer'),
  card: t('paymentMethodCard'),
  rent: t('financeCenterRent'),
  equipment: t('financeCenterEquipment'),
  supplies: t('financeCenterSupplies'),
  utilities: t('financeCenterUtilities'),
  software: t('financeCenterSoftware'),
  taxes: t('financeCenterTaxes'),
  transport: t('financeCenterTransport'),
  maintenance: t('financeCenterMaintenance'),
  other: t('financeCenterOther'),
  payrollCategory: t('financeCenterPayrollCategory'),
  studentPayments: t('financeCenterStudentPayments'),
  all: t('allConversations'),
  incoming: t('financeCenterIncoming'),
  outgoing: t('financeCenterOutgoing'),
});
