FROM postgres:17-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193

RUN apk add --no-cache zip unzip

COPY scripts/create-production-backup.sh /usr/local/bin/create-production-backup
COPY scripts/run-backup-scheduler.sh /usr/local/bin/run-backup-scheduler

RUN chmod 0555 \
    /usr/local/bin/create-production-backup \
    /usr/local/bin/run-backup-scheduler

ENTRYPOINT ["/usr/local/bin/run-backup-scheduler"]
