import { useTranslation } from '@/hooks/useTranslation';

export function useCeoCopy() {
  const { t } = useTranslation();

  return {
    module: {
      audit: t('auditLog'),
    },
    student: {
      learningStatus: t('studentLearningStatus'),
      status: t('status'),
      studying: t('studentStatusStudying'),
      paused: t('studentStatusPaused'),
      completed: t('studentStatusCompleted'),
      expelled: t('studentStatusExpelled'),
      churnReason: t('studentChurnReason'),
      chooseReason: t('chooseArchiveReason'),
      relocation: t('studentChurnRelocation'),
      price: t('studentChurnPrice'),
      quality: t('studentChurnQuality'),
      scheduleConflict: t('studentChurnScheduleConflict'),
      lostInterest: t('studentChurnLostInterest'),
      saving: t('saving'),
      saveStatus: t('studentSaveStatus'),
      updated: t('studentStatusUpdated'),
      updateFailed: t('studentStatusUpdateFailed'),
      overdueStudents: t('studentsWithOverduePayments'),
      lowAttendanceStudents: t('studentsWithLowAttendance'),
    },
    settings: {
      saved: t('ceoGoalsSaved'),
      failed: t('ceoGoalsSaveFailed'),
      title: t('ceoGoalsTitle'),
      noGroupsWithoutTeacher: t('noGroupsWithoutTeacher'),
      allGroupsStaffed: t('allActiveGroupsStaffed'),
      description: t('ceoGoalsDescription'),
      save: t('saveGoals'),
      revenue: t('targetMonthlyRevenue'),
      newLeads: t('targetMonthlyNewLeads'),
      maxCac: t('maximumCac'),
      maxCpl: t('maximumCpl'),
      roas: t('targetRoas'),
      attendance: t('targetAttendance'),
      nps: t('targetNps'),
      sum: t('currencyUzs'),
      leads: t('leadCountMany'),
      phoneVisibility: t('salesLeadVisibility'),
      ownLeadsOnly: t('ownAndUnassignedLeads'),
      maskUntilAssigned: t('maskLeadsUntilAssigned'),
    },
    dashboard: {
      taskCreated: t('adminAlertTaskCreated'),
      taskFailed: t('taskCreateFailed'),
      planFact: t('planAndActual'),
      revenue: t('revenue'),
      planUnset: t('planNotSet'),
      newLeads: t('newLeads'),
      plan: t('planLabel'),
      createTask: t('createTask'),
      churnReasons: t('monthlyChurnReasons'),
      churnStatuses: t('churnStatusesDescription'),
      noChurn: t('noChurnThisMonth'),
      open: t('openLabel'),
      students: t('studentsCount'),
      escalatedTasks: t('escalatedTasksTitle'),
      escalatedTasksDetail: t('escalatedTasksDescription'),
    },
    audit: {
      created: t('auditActionCreated'),
      deleted: t('auditActionDeleted'),
      refund: t('auditActionRefunded'),
      approved: t('auditActionApproved'),
      changed: t('auditActionChanged'),
      lead: t('lead'),
      student: t('student'),
      payment: t('payment'),
      group: t('group'),
      schedule: t('schedule'),
      expense: t('auditEntityExpense'),
      task: t('auditEntityTask'),
      kpi: t('ceoGoalsTitle'),
      yes: t('yes'),
      no: t('no'),
      title: t('auditLog'),
      subtitle: t('auditLogDescription'),
      refresh: t('adminRefresh'),
      history: t('auditHistory'),
      integrations: t('navIntegrations'),
      employee: t('financeCenterEmployee'),
      allEmployees: t('allEmployees'),
      action: t('auditAction'),
      allActions: t('allActions'),
      object: t('auditObject'),
      allObjects: t('allObjects'),
      leads: t('navLeads'),
      students: t('students'),
      payments: t('navPayments'),
      groups: t('navGroups'),
      fromDate: t('fromDate'),
      toDate: t('toDate'),
      reset: t('reset'),
      loading: t('auditLoading'),
      shown: t('auditShown'),
      lastEvents: t('auditLastEvents'),
      date: t('dateColumn'),
      changes: t('changes'),
      system: t('system'),
      viewChanges: t('viewChanges'),
      noResults: t('noAuditResults'),
      integrationLogs: t('integrationLogs'),
      integrationDescription: t('integrationLogsDescription'),
      source: t('source'),
      status: t('status'),
      message: t('message'),
      time: t('time'),
      noErrors: t('noErrors'),
      noIntegrationLogs: t('noIntegrationLogs'),
      recordChanges: t('recordChanges'),
      field: t('field'),
      before: t('before'),
      after: t('after'),
      noDiff: t('noAuditDiff'),
    },
  } as const;
}
