import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

export const createMetaMarketingTables = (references: {
  leadId: AnyPgColumn;
  conversationId: AnyPgColumn;
}) => {
  const metaLeadAttributions = pgTable('meta_lead_attributions', {
    id: serial('id').primaryKey(),
    leadId: integer('lead_id').references(() => references.leadId, { onDelete: 'set null' }),
    conversationId: integer('conversation_id').references(() => references.conversationId, { onDelete: 'cascade' }),
    leadgenId: varchar('leadgen_id', { length: 255 }),
    formId: varchar('form_id', { length: 255 }),
    provider: varchar('provider', { length: 40 }).notNull().default('meta'),
    channel: varchar('channel', { length: 40 }).notNull().default('instagram'),
    touchType: varchar('touch_type', { length: 40 }).notNull().default('first_touch'),
    adId: varchar('ad_id', { length: 120 }),
    adName: varchar('ad_name', { length: 500 }),
    adsetId: varchar('adset_id', { length: 120 }),
    adsetName: varchar('adset_name', { length: 500 }),
    campaignId: varchar('campaign_id', { length: 120 }),
    campaignName: varchar('campaign_name', { length: 500 }),
    creativeId: varchar('creative_id', { length: 120 }),
    creativeName: varchar('creative_name', { length: 500 }),
    creativeTitle: text('creative_title'),
    creativeBody: text('creative_body'),
    mediaType: varchar('media_type', { length: 80 }),
    hookName: varchar('hook_name', { length: 500 }),
    placement: varchar('placement', { length: 120 }),
    referralSource: varchar('referral_source', { length: 120 }),
    referralType: varchar('referral_type', { length: 120 }),
    referralRef: text('referral_ref'),
    sourceUrl: text('source_url'),
    thumbnailUrl: text('thumbnail_url'),
    utmSource: varchar('utm_source', { length: 500 }),
    utmMedium: varchar('utm_medium', { length: 500 }),
    utmCampaign: varchar('utm_campaign', { length: 500 }),
    utmContent: varchar('utm_content', { length: 500 }),
    utmTerm: varchar('utm_term', { length: 500 }),
    utmValues: jsonb('utm_values').$type<Record<string, string>>().notNull().default({}),
    utmDerived: boolean('utm_derived').notNull().default(false),
    rawPayload: jsonb('raw_payload'),
    enrichmentStatus: varchar('enrichment_status', { length: 30 }).notNull().default('pending'),
    enrichmentAttempts: integer('enrichment_attempts').notNull().default(0),
    nextEnrichmentAt: timestamp('next_enrichment_at').notNull().defaultNow(),
    enrichedAt: timestamp('enriched_at'),
    enrichmentError: text('enrichment_error'),
    capturedAt: timestamp('captured_at').notNull().defaultNow(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  }, (table) => ({
    conversationTouchUnique: uniqueIndex('meta_lead_attributions_conversation_touch_unique').on(table.conversationId, table.touchType),
    leadgenTouchUnique: uniqueIndex('meta_lead_attributions_leadgen_touch_unique')
      .on(table.leadgenId, table.touchType)
      .where(sql`${table.leadgenId} IS NOT NULL AND BTRIM(${table.leadgenId}) <> ''`),
    formIdx: index('meta_lead_attributions_form_idx').on(table.formId),
    leadIdx: index('meta_lead_attributions_lead_idx').on(table.leadId, table.capturedAt),
    adIdx: index('meta_lead_attributions_ad_idx').on(table.adId),
    enrichmentIdx: index('meta_lead_attributions_enrichment_idx').on(table.enrichmentStatus, table.nextEnrichmentAt),
    touchTypeCheck: check('meta_lead_attributions_touch_type_check', sql`${table.touchType} IN ('first_touch')`),
    enrichmentStatusCheck: check(
      'meta_lead_attributions_enrichment_status_check',
      sql`${table.enrichmentStatus} IN ('pending', 'processing', 'enriched', 'failed', 'not_required')`,
    ),
    enrichmentAttemptsCheck: check('meta_lead_attributions_enrichment_attempts_check', sql`${table.enrichmentAttempts} >= 0`),
  }));

  const metaConversionEvents = pgTable('meta_conversion_events', {
    id: serial('id').primaryKey(),
    leadId: integer('lead_id').references(() => references.leadId, { onDelete: 'set null' }),
    attributionId: integer('attribution_id').references(() => metaLeadAttributions.id, { onDelete: 'set null' }),
    eventId: varchar('event_id', { length: 255 }).notNull(),
    eventName: varchar('event_name', { length: 120 }).notNull(),
    crmStage: varchar('crm_stage', { length: 80 }).notNull(),
    eventTime: timestamp('event_time').notNull(),
    actionSource: varchar('action_source', { length: 80 }).notNull().default('business_messaging'),
    messagingChannel: varchar('messaging_channel', { length: 40 }).notNull().default('instagram'),
    userData: jsonb('user_data').$type<Record<string, unknown>>().notNull().default({}),
    customData: jsonb('custom_data').$type<Record<string, unknown>>().notNull().default({}),
    status: varchar('status', { length: 30 }).notNull().default('pending'),
    attemptCount: integer('attempt_count').notNull().default(0),
    nextAttemptAt: timestamp('next_attempt_at').notNull().defaultNow(),
    lastAttemptAt: timestamp('last_attempt_at'),
    sentAt: timestamp('sent_at'),
    responsePayload: jsonb('response_payload'),
    errorMessage: text('error_message'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  }, (table) => ({
    eventUnique: uniqueIndex('meta_conversion_events_event_unique').on(table.eventId),
    leadIdx: index('meta_conversion_events_lead_idx').on(table.leadId, table.eventTime),
    dispatchIdx: index('meta_conversion_events_dispatch_idx').on(table.status, table.nextAttemptAt),
    statusCheck: check('meta_conversion_events_status_check', sql`${table.status} IN ('pending', 'processing', 'sent', 'failed')`),
    attemptCountCheck: check('meta_conversion_events_attempt_count_check', sql`${table.attemptCount} >= 0`),
  }));

  return { metaLeadAttributions, metaConversionEvents };
};
