-- Run with psql -v ON_ERROR_STOP=1. Everything, including the test schema,
-- is rolled back. No production tables, sequences or functions are used.
BEGIN;
CREATE SCHEMA codex_demo_pipeline_verification;
SET LOCAL search_path TO codex_demo_pipeline_verification;
CREATE TABLE academy_lead_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  color text,
  sort_order integer NOT NULL DEFAULT 0,
  is_pipeline boolean NOT NULL DEFAULT true,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz DEFAULT now()
);
INSERT INTO academy_lead_statuses (code, name, color, sort_order, is_pipeline, is_active)
VALUES ('ne_prishli_na_vstrechu', 'Custom no-show label', '#112233', 80, false, false);

\ir ../../migrations/0099_protect_demo_pipeline_statuses.sql

DO $$
DECLARE stage_code text; mutation text; failure text; count_rows integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM academy_lead_statuses
    WHERE id = 1 AND code = 'ne_prishli_na_vstrechu' AND name = 'Custom no-show label'
      AND color = '#112233' AND sort_order = 80 AND is_pipeline AND is_active AND is_system) THEN
    RAISE EXCEPTION 'Migration must reuse and protect the existing stage without renaming it';
  END IF;
  SELECT count(*) INTO count_rows FROM academy_lead_statuses;
  IF count_rows <> 2 THEN RAISE EXCEPTION 'Expected exactly two protected stages'; END IF;

  FOREACH stage_code IN ARRAY ARRAY['demo_attended', 'ne_prishli_na_vstrechu'] LOOP
    FOREACH mutation IN ARRAY ARRAY[
      'DELETE FROM academy_lead_statuses WHERE code = $1',
      'UPDATE academy_lead_statuses SET is_active = false WHERE code = $1',
      'UPDATE academy_lead_statuses SET is_pipeline = false WHERE code = $1',
      'UPDATE academy_lead_statuses SET is_system = false WHERE code = $1',
      'UPDATE academy_lead_statuses SET code = ''renamed_code'' WHERE code = $1'
    ] LOOP
      failure := NULL;
      BEGIN
        EXECUTE mutation USING stage_code;
      EXCEPTION WHEN raise_exception THEN
        failure := SQLERRM;
      END;
      IF failure IS NULL OR failure NOT IN ('systemPipelineStageCannotBeDeleted', 'demoPipelineStageProtected') THEN
        RAISE EXCEPTION 'Protected mutation was not rejected: %, %', mutation, failure;
      END IF;
    END LOOP;
  END LOOP;

  UPDATE academy_lead_statuses SET name = 'New label', color = '#ffffff', sort_order = 120;
  GET DIAGNOSTICS count_rows = ROW_COUNT;
  IF count_rows <> 2 THEN RAISE EXCEPTION 'Appearance edits must remain available'; END IF;
  INSERT INTO academy_lead_statuses (code, name) VALUES ('custom', 'Custom');
  DELETE FROM academy_lead_statuses WHERE code = 'custom';
  GET DIAGNOSTICS count_rows = ROW_COUNT;
  IF count_rows <> 1 THEN RAISE EXCEPTION 'Custom stage deletion must still work'; END IF;
  RAISE NOTICE 'PASS: migration preserves existing data; both stages protected; appearance and custom deletion work';
END;
$$;
ROLLBACK;
