// Copy for the CEO control center. Kept next to UI primitives so the
// product-specific Russian terminology stays consistent across its screens.
export const ceoCopy = {
  workspace: {
    audit: 'Журнал действий',
  },
  student: {
    learningStatus: 'Статус обучения',
    status: 'Статус',
    studying: 'Обучается',
    paused: 'Заморожен',
    completed: 'Завершил',
    expelled: 'Отчислен',
    churnReason: 'Причина ухода',
    chooseReason: 'Выберите причину',
    relocation: 'Переезд',
    price: 'Дорого',
    quality: 'Не понравилось качество',
    scheduleConflict: 'Конфликт расписания',
    lostInterest: 'Потеря интереса',
    saving: 'Сохраняем…',
    saveStatus: 'Сохранить статус',
    updated: 'Статус ученика обновлён',
    updateFailed: 'Не удалось обновить статус ученика',
    overdueStudents: 'Ученики с просроченными оплатами',
    lowAttendanceStudents: 'Ученики с низкой посещаемостью',
  },
  settings: {
    saved: 'Цели и KPI сохранены',
    failed: 'Не удалось сохранить цели',
    title: 'Цели и KPI',
    noGroupsWithoutTeacher: 'Групп без преподавателя нет',
    allGroupsStaffed: 'Все активные группы уже укомплектованы.',
    description: 'Цели используются в CEO Dashboard и аналитике для план/факта и цветов показателей.',
    save: 'Сохранить цели',
    revenue: 'Целевая выручка на месяц',
    newLeads: 'Целевое количество новых лидов',
    maxCac: 'Допустимый CAC',
    maxCpl: 'Допустимый CPL',
    roas: 'Целевой ROAS',
    attendance: 'Норма посещаемости',
    nps: 'Целевой NPS',
    sum: 'сум',
    leads: 'лидов',
    phoneVisibility: 'Видимость телефонов для продаж',
    ownLeadsOnly: 'Только свои лиды',
    maskUntilAssigned: 'Маскировать до взятия в работу',
    workHours: 'Рабочее время доступа',
    workdayStart: 'Начало дня',
    workdayEnd: 'Конец дня',
    workdays: 'Рабочие дни',
  },
  dashboard: {
    taskCreated: 'Задача создана и назначена ответственному сотруднику',
    taskFailed: 'Не удалось создать задачу',
    planFact: 'План и факт',
    revenue: 'Выручка',
    planUnset: 'План не задан',
    newLeads: 'Новые лиды',
    plan: 'План:',
    createTask: 'Создать задачу',
    churnReasons: 'Причины оттока за месяц',
    churnStatuses: 'Статусы «заморожен» и «отчислен»',
    noChurn: 'За текущий месяц нет зафиксированного оттока.',
    open: 'Открыть:',
    students: 'учеников',
    escalatedTasks: 'Просроченные задачи 24+ ч',
    escalatedTasksDetail: 'Задачи, по которым уже отправлена эскалация руководителю.',
  },
  audit: {
    created: 'Создание', deleted: 'Удаление', refund: 'Возврат оплаты', approved: 'Одобрение расхода', changed: 'Изменение',
    lead: 'Лид', student: 'Ученик', payment: 'Оплата', group: 'Группа', schedule: 'Расписание', expense: 'Расход', task: 'Задача', kpi: 'Цели и KPI', yes: 'Да', no: 'Нет',
    title: 'Журнал действий', subtitle: 'История изменений и состояние интеграций академии.', refresh: 'Обновить', history: 'История изменений', integrations: 'Интеграции',
    employee: 'Сотрудник', allEmployees: 'Все сотрудники', action: 'Действие', allActions: 'Все действия', object: 'Объект', allObjects: 'Все объекты',
    leads: 'Лиды', students: 'Ученики', payments: 'Оплаты', groups: 'Группы', fromDate: 'С даты', toDate: 'По дату', reset: 'Сбросить',
    loading: 'Загружаем события…', shown: 'Показано', lastEvents: 'последних событий', date: 'Дата', changes: 'Изменения', system: 'Система',
    viewChanges: 'Посмотреть изменения', noResults: 'По этим фильтрам действий не найдено.', integrationLogs: 'Логи интеграций', integrationDescription: 'Ошибки и последние события ботов и Instagram.',
    source: 'Источник', status: 'Статус', message: 'Сообщение', time: 'Время', noErrors: 'Без ошибок', noIntegrationLogs: 'Логов интеграций пока нет.',
    recordChanges: 'Изменения в записи', field: 'Поле', before: 'Было', after: 'Стало', noDiff: 'Для этого действия нет полей сравнения.',
  },
} as const;
