// Copy for the CEO control center. Kept next to UI primitives so the
// product-specific Russian terminology stays consistent across its screens.
export const ceoCopy = {
  workspace: {
    desk: 'Рабочий стол',
    deskTitle: 'Рабочий стол руководителя',
    departments: 'Отделы компании',
    sales: 'Продажи',
    marketing: 'Маркетинг',
    analytics: 'Аналитика',
    teachers: 'Преподаватели',
    audit: 'Журнал действий',
    finance: 'Финансы',
    payroll: 'Зарплаты',
  },
  student: {
    learningStatus: 'Статус обучения',
    status: 'Статус',
    studying: 'Обучается',
    paused: 'Заморожен',
    completed: 'Завершил',
    expelled: 'Отчислен',
    churnReason: 'Причина ухода',
    chooseReason: 'Выберите причину',
    relocation: 'Переезд',
    price: 'Дорого',
    quality: 'Не понравилось качество',
    scheduleConflict: 'Конфликт расписания',
    lostInterest: 'Потеря интереса',
    saving: 'Сохраняем…',
    saveStatus: 'Сохранить статус',
    updated: 'Статус ученика обновлён',
    updateFailed: 'Не удалось обновить статус ученика',
    overdueStudents: 'Ученики с просроченными оплатами',
    lowAttendanceStudents: 'Ученики с низкой посещаемостью',
  },
  settings: {
    saved: 'Цели и KPI сохранены',
    failed: 'Не удалось сохранить цели',
    title: 'Цели и KPI',
    noGroupsWithoutTeacher: 'Групп без преподавателя нет',
    allGroupsStaffed: 'Все активные группы уже укомплектованы.',
    description: 'Цели используются в CEO Dashboard и аналитике для план/факта и цветов показателей.',
    save: 'Сохранить цели',
    revenue: 'Целевая выручка на месяц',
    newLeads: 'Целевое количество новых лидов',
    maxCac: 'Допустимый CAC',
    maxCpl: 'Допустимый CPL',
    roas: 'Целевой ROAS',
    attendance: 'Норма посещаемости',
    nps: 'Целевой NPS',
    sum: 'сум',
    leads: 'лидов',
    commission: 'Комиссия отдела продаж',
    minGroupFill: 'Минимальная заполняемость группы',
    currentCash: 'Текущий остаток денег',
    phoneVisibility: 'Видимость телефонов для продаж',
    ownLeadsOnly: 'Только свои лиды',
    maskUntilAssigned: 'Маскировать до взятия в работу',
    workHours: 'Рабочее время доступа',
    workdayStart: 'Начало дня',
    workdayEnd: 'Конец дня',
    workdays: 'Рабочие дни',
    roomRentPerHour: 'Аренда кабинета за час',
  },
  payroll: {
    title: 'Зарплаты и мотивация',
    subtitle: 'Расчёт по проведённым урокам и ручным оплатам без финансовых интеграций.',
    period: 'Расчётный месяц',
    pending: 'К выплате',
    paid: 'Уже выплачено',
    total: 'Фонд за месяц',
    employee: 'Сотрудник',
    type: 'Тип',
    teacher: 'Преподаватель',
    manager: 'Менеджер продаж',
    lessons: 'Проведено уроков',
    rate: 'Ставка за урок',
    salary: 'Оклад',
    commission: 'Комиссия',
    commissionBase: 'Оплаты менеджера',
    payout: 'Выплатить',
    payoutDone: 'Выплата зафиксирована как расход',
    payoutFailed: 'Не удалось зафиксировать выплату',
    rateTitle: 'Ставки преподавателей',
    rateDescription: 'Ставка применяется к каждому уроку со статусом «проведён».',
    saveRate: 'Сохранить ставку',
    rateSaved: 'Ставка преподавателя сохранена',
    noEntries: 'За этот месяц нет сотрудников для расчёта.',
  },
  profitability: {
    title: 'Убыточные группы',
    subtitle: 'Группы ниже порога заполняемости и с отрицательной прибылью.',
    noLosses: 'Убыточных групп по текущим данным нет.',
    profit: 'Прибыль',
    revenue: 'Оплаты учеников',
    teacherCost: 'Зарплата преподавателя',
    rentCost: 'Аренда кабинета',
    fill: 'Заполненность',
  },
  dashboard: {
    taskCreated: 'Задача создана и назначена ответственному сотруднику',
    taskFailed: 'Не удалось создать задачу',
    planFact: 'План и факт',
    revenue: 'Выручка',
    planUnset: 'План не задан',
    newLeads: 'Новые лиды',
    plan: 'План:',
    createTask: 'Создать задачу',
    churnReasons: 'Причины оттока за месяц',
    churnStatuses: 'Статусы «заморожен» и «отчислен»',
    noChurn: 'За текущий месяц нет зафиксированного оттока.',
    discounts: 'Выдано скидок за месяц',
    discountsDescription: 'Промокоды, семейные и реферальные скидки',
    open: 'Открыть:',
    students: 'учеников',
    escalatedTasks: 'Просроченные задачи 24+ ч',
    escalatedTasksDetail: 'Задачи, по которым уже отправлена эскалация руководителю.',
  },
  audit: {
    created: 'Создание', deleted: 'Удаление', refund: 'Возврат оплаты', approved: 'Одобрение расхода', changed: 'Изменение',
    lead: 'Лид', student: 'Ученик', payment: 'Оплата', group: 'Группа', schedule: 'Расписание', expense: 'Расход', task: 'Задача', kpi: 'Цели и KPI', yes: 'Да', no: 'Нет',
    title: 'Журнал действий', subtitle: 'История изменений и состояние интеграций академии.', refresh: 'Обновить', history: 'История изменений', integrations: 'Интеграции',
    employee: 'Сотрудник', allEmployees: 'Все сотрудники', action: 'Действие', allActions: 'Все действия', object: 'Объект', allObjects: 'Все объекты',
    leads: 'Лиды', students: 'Ученики', payments: 'Оплаты', groups: 'Группы', fromDate: 'С даты', toDate: 'По дату', reset: 'Сбросить',
    loading: 'Загружаем события…', shown: 'Показано', lastEvents: 'последних событий', date: 'Дата', changes: 'Изменения', system: 'Система',
    viewChanges: 'Посмотреть изменения', noResults: 'По этим фильтрам действий не найдено.', integrationLogs: 'Логи интеграций', integrationDescription: 'Ошибки и последние события ботов и Instagram.',
    source: 'Источник', status: 'Статус', message: 'Сообщение', time: 'Время', noErrors: 'Без ошибок', noIntegrationLogs: 'Логов интеграций пока нет.',
    recordChanges: 'Изменения в записи', field: 'Поле', before: 'Было', after: 'Стало', noDiff: 'Для этого действия нет полей сравнения.',
  },
  finance: {
    expenseApproved: 'Расход одобрен', expenseApproveFailed: 'Не удалось одобрить расход', refunded: 'Платёж отменён, возврат зафиксирован', refundFailed: 'Не удалось оформить возврат', payment: 'Оплата',
    title: 'Финансы', subtitle: 'Единый реестр денежных потоков, согласование маркетинговых расходов и контроль скидок.', register: 'Реестр транзакций', pendingExpenses: 'Расходы на согласовании',
    confirmedRevenue: 'Подтверждённая выручка', approvedExpenses: 'Одобренные расходы', pnl: 'P&L', discountsMonth: 'Скидки за месяц',
    payrollExpenses: 'Выплаты сотрудникам',
    allTransactions: 'Все транзакции', allTransactionsDescription: 'Приходы от учеников и маркетинговые расходы в одной ленте.', all: 'Все', incomes: 'Приходы', expenses: 'Расходы',
    date: 'Дата', type: 'Тип', description: 'Описание', status: 'Статус', amount: 'Сумма', income: 'Приход', expense: 'Расход', approved: 'Одобрен', paid: 'Оплачен', refund: 'Возврат', pending: 'На согласовании',
    noTransactions: 'Транзакций пока нет.', marketingExpenses: 'Маркетинговые расходы', marketingExpensesDescription: 'Расходы попадают в ROAS и P&L только после вашего подтверждения.',
    campaign: 'Кампания', channel: 'Канал', createdBy: 'Добавил', noCampaign: 'Без кампании', approve: 'Одобрить', approvedPast: 'Одобрено', noExpenses: 'Маркетинговых расходов пока нет.',
    refundTitle: 'Отменить платёж / оформить возврат', refundDescription: 'Комментарий обязателен: это действие исключит оплату из финансовых показателей.', comment: 'Комментарий', refundReason: 'Причина возврата', cancel: 'Отмена', processRefund: 'Оформить возврат',
  },
  analytics: {
    month: 'Месяц:',
    plan: 'План:',
    goalNoHigher: 'Цель: не выше',
    goal: 'Цель:',
    nps: 'NPS',
  },
} as const;
